INSERT INTO "GROUPS" (NAME)
VALUES ('Fish');
INSERT INTO "GROUPS" (NAME)
VALUES ('Amphibians');
INSERT INTO "GROUPS" (NAME)
VALUES ('Reptiles');
INSERT INTO "GROUPS" (NAME)
VALUES ('Birds');
INSERT INTO "GROUPS" (NAME)
VALUES ('Mammals');

INSERT INTO ANIMALS (SCIENTIFIC_NAME, SPECIE, SIZE, MASS, STATUS, GROUP_ID)
VALUES ('Panthera Leo', 'Lion', 1.8, 190.5, 'ACTIVE', 5);
INSERT INTO ANIMALS (SCIENTIFIC_NAME, SPECIE, SIZE, MASS, STATUS, GROUP_ID)
VALUES ('Ailuropoda Melanoleuca', 'Giant Panda', 1.6, 100.0, 'INACTIVE', 5);
INSERT INTO ANIMALS (SCIENTIFIC_NAME, SPECIE, SIZE, MASS, STATUS, GROUP_ID)
VALUES ('Loxodonta Africana', 'African Elephant', 3.2, 6000.0, 'ACTIVE', 5);

INSERT INTO ANIMALS (SCIENTIFIC_NAME, SPECIE, SIZE, MASS, STATUS, GROUP_ID)
VALUES ('Aquila chrysaetos', 'Golden Eagle', 2.3, 6.5, 'ACTIVE', 4);
INSERT INTO ANIMALS (SCIENTIFIC_NAME, SPECIE, SIZE, MASS, STATUS, GROUP_ID)
VALUES ('Struthio camelus', 'Ostrich', 2.7, 150.0, 'ACTIVE', 4);

INSERT INTO ANIMALS (SCIENTIFIC_NAME, SPECIE, SIZE, MASS, STATUS, GROUP_ID)
VALUES ('Carcharodon carcharias', 'Great White Shark', 6.0, 1100.0, 'ACTIVE', 1);

INSERT INTO ANIMALS (SCIENTIFIC_NAME, SPECIE, SIZE, MASS, STATUS, GROUP_ID)
VALUES ('Rana temporaria', 'European Common Frog', 0.1, 0.03, 'ACTIVE', 2);

INSERT INTO ANIMALS (SCIENTIFIC_NAME, SPECIE, SIZE, MASS, STATUS, GROUP_ID)
VALUES ('Crocodylus porosus', 'Saltwater Crocodile', 5.5, 1000.0, 'ACTIVE', 3);