CREATE TABLE GROUPS
(
    ID   BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (ID)
);

CREATE TABLE ANIMALS
(
    ID              BIGINT AUTO_INCREMENT NOT NULL,
    SCIENTIFIC_NAME VARCHAR(255) NOT NULL,
    SPECIE          VARCHAR(255) NOT NULL,
    SIZE            DOUBLE       NOT NULL,
    MASS            DOUBLE       NOT NULL,
    STATUS          VARCHAR(255) NOT NULL,
    GROUP_ID        BIGINT,
    CONSTRAINT pk_animals PRIMARY KEY (ID)
);

ALTER TABLE ANIMALS
    ADD CONSTRAINT FK_ANIMALS_ON_GROUP FOREIGN KEY (GROUP_ID) REFERENCES "GROUPS" (ID);